name: Lint

on:
  push:
    branches: [main]
    paths:
      - grammar.js
  pull_request:
    paths:
      - grammar.js
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
